<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBw1sQA8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBw1sQA8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBw1sQA8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBw1sQA8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBw1sQA8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Bw1sQA8',
    'container.build_id' => 'ae9c5126',
    'container.build_time' => 1552383076,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBw1sQA8');
