<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNvV1qn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNvV1qn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNvV1qn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNvV1qn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNNvV1qn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NNvV1qn',
    'container.build_id' => 'a35997f3',
    'container.build_time' => 1552318512,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNvV1qn');
